en:
  quotes:
    - text: "The only way to do great work is to love what you do."
      author: "Steve Jobs"
    - text: "Life is what happens when you're busy making other plans."
      author: "John Lennon"
    - text: "In the end, we will remember not the words of our enemies, but the silence of our friends."
      author: "Martin Luther King Jr."
    - text: "The best way to predict the future is to invent it."
      author: "Alan Kay"
    - text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment."
      author: "Ralph Waldo Emerson"
    - text: "The purpose of our lives is to be happy."
      author: "Dalai Lama"
    - text: "Life is either a daring adventure or nothing at all."
      author: "Helen Keller"
    - text: "The only limit to our realization of tomorrow is our doubts of today."
      author: "Franklin D. Roosevelt"
    - text: "You miss 100% of the shots you don't take."
      author: "Wayne Gretzky"
    - text: "Success is not final, failure is not fatal: It is the courage to continue that counts."
      author: "Winston Churchill"

jp:
  quotes:
    - text: "素晴らしい仕事をする唯一の方法は、それを愛することです。"
      author: "スティーブ・ジョブズ"
    - text: "人生は、他の計画を立てているときに起こるものです。"
      author: "ジョン・レノン"
    - text: "最後には、敵の言葉ではなく、友人の沈黙を思い出すことになるでしょう。"
      author: "マーティン・ルーサー・キング・ジュニア"
    - text: "未来を予測する最良の方法は、それを発明することです。"
      author: "アラン・ケイ"
    - text: "常に他の何かにしようとする世界の中で自分自身でいることが、最大の成就です。"
      author: "ラルフ・ワルド・エマーソン"
    - text: "私たちの人生の目的は、幸せであることです。"
      author: "ダライ・ラマ"
    - text: "人生は、冒険をするか何もないかのどちらかです。"
      author: "ヘレン・ケラー"
    - text: "明日を実現するための唯一の制限は、今日の疑念です。"
      author: "フランクリン・D・ルーズベルト"
    - text: "打たないショットは100％外れる。"
      author: "ウェイン・グレツキー"
    - text: "成功は最終的なものではなく、失敗は致命的ではありません。重要なのは、続ける勇気です。"
      author: "ウィンストン・チャーチル"
